# Generated by Django 5.0.2 on 2024-03-16 16:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_url', models.CharField(max_length=200)),
                ('brand_logo', models.ImageField(upload_to='')),
                ('about_brand', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_pic', models.ImageField(upload_to='')),
                ('category_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_pic', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('authority_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche_name', models.CharField(max_length=200)),
                ('niche_img', models.ImageField(upload_to='')),
                ('niche_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key_features', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('connectivity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_email', models.EmailField(max_length=200)),
                ('supplier_phone', models.IntegerField()),
                ('supplier_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pic', models.ImageField(upload_to='')),
                ('type_name', models.CharField(max_length=200)),
                ('type_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(max_length=300, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quality_stars', models.IntegerField(null=True)),
                ('design_stars', models.IntegerField(null=True)),
                ('general_stars', models.IntegerField(null=True)),
                ('comment', models.TextField(max_length=500, null=True)),
                ('rating_created_date', models.DateTimeField(auto_now_add=True)),
                ('rating_updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_model', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_img_mini', models.ImageField(upload_to='')),
                ('product_population', models.CharField(max_length=200)),
                ('product_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_color', models.CharField(max_length=200)),
                ('product_material', models.CharField(max_length=200)),
                ('product_availability', models.BooleanField()),
                ('product_added_date', models.DateTimeField(auto_now_add=True)),
                ('last_bought', models.DateTimeField(auto_now=True)),
                ('units', models.IntegerField()),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brand')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
                ('product_niche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.niche')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.rating')),
                ('product_specifications', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.specification')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.type')),
            ],
        ),
    ]
