# Generated by Django 5.0.2 on 2024-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img_mini',
        ),
        migrations.AddField(
            model_name='type',
            name='type_banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
