# Generated by Django 5.0.2 on 2024-03-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_brand_id_alter_employees_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='Summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
