# Generated by Django 5.0.2 on 2024-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_specification_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
