# Generated by Django 5.0.2 on 2024-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_previous',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
